[package]
authors = ["Bart Massey <bart.massey@gmail.com>"]
edition = "2018"
name = "dimacs-color"
version = "0.1.0"
[dependencies]
gumdrop = "0.8"
once_cell = "1.5"
rand = "0.8.3"

[dependencies.dimacs-graph]
branch = "main"
git = "http://github.com/BartMassey/dimacs-graph"
version = "*"
